### ISSUE TITLE
00 Set Default Network Setting

### ISSUE THREAD

**Issue by geowcz** [everknight/LargeODcost#4] opened 2020-10-02 16:27 UTC
![image](https://user-images.githubusercontent.com/52430000/94946791-44c66d80-04a2-11eb-9654-35dfc97405e0.png)

**Comment by everknight** [comment] 2020-10-02 19:52
Bug is caused by inconsistant use of tabs and spaces.
Fixed in update e449703

**Closed as completed by everknight** 2020-10-02 19:52 UTC
